//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorClient.CalculatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorServiceReference.ICalulator")]
    public interface ICalulator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalulator/AddNumber", ReplyAction="http://tempuri.org/ICalulator/AddNumberResponse")]
        double AddNumber(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalulator/AddNumber", ReplyAction="http://tempuri.org/ICalulator/AddNumberResponse")]
        System.Threading.Tasks.Task<double> AddNumberAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalulator/SubNumber", ReplyAction="http://tempuri.org/ICalulator/SubNumberResponse")]
        double SubNumber(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalulator/SubNumber", ReplyAction="http://tempuri.org/ICalulator/SubNumberResponse")]
        System.Threading.Tasks.Task<double> SubNumberAsync(double num1, double num2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalulatorChannel : CalculatorClient.CalculatorServiceReference.ICalulator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalulatorClient : System.ServiceModel.ClientBase<CalculatorClient.CalculatorServiceReference.ICalulator>, CalculatorClient.CalculatorServiceReference.ICalulator {
        
        public CalulatorClient() {
        }
        
        public CalulatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalulatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalulatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalulatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AddNumber(double num1, double num2) {
            return base.Channel.AddNumber(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> AddNumberAsync(double num1, double num2) {
            return base.Channel.AddNumberAsync(num1, num2);
        }
        
        public double SubNumber(double num1, double num2) {
            return base.Channel.SubNumber(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> SubNumberAsync(double num1, double num2) {
            return base.Channel.SubNumberAsync(num1, num2);
        }
    }
}
